location                 = "West Europe"
account_tier             = "Standard"
account_replication_type = "LRS"
resource_group_name      = "resource-group-terraform"
storage_account_name     = "storage-account-terraform"
container_name           = "container-terraform" 
